# 从臂注册表 — 部署前修改
# 每台从臂的 id 必须与对应 AGX Orin 上的 robot_name 严格一致
slaves:
  - id: ar5_01
    ip: 10.18.16.18
    network_interface: enp2s0
    type: ar5
  - id: ar5_02
    ip: 10.18.17.17
    network_interface: enp2s0
    type: ar5
